
name: CI

on:
  push:
    branches: [ "UI-Tasks" ]
  pull_request:
    branches: [ "UI-Tasks" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v4.1.0
#      - with:
#          record: true
#          env:
#            CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
#            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
