name: Cypress tests

on:
  # Triggers the workflow on push or pull request events but only for the "UI-Tasks" branch
  push:
    branches: [ "UI-Tasks" ]
  pull_request:
    branches: [ "UI-Tasks" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v4.1.0
      -  run: npx cypress run --record --key 1aac12fe-4319-4625-8dff-4ba2a6736717

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos


      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
